# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- development
- master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs: 
      - job: Build
        displayName: Build
        variables:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'
          solution: Sources\WiLinq.sln'
          projects: '**/*.csproj'
          testProjects: '**/*.*Tests.csproj'
        steps:
        - task: GitVersion@4
          displayName: GitVersion
          inputs:
            preferBundledVersion: false
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '$(solution)'
            feedsToUse: 'select'
        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: VSTest@2
          inputs:
            testSelector: 'testAssemblies'
            testAssemblyVer2: |
              **\*.Tests.dll
              !**\*TestAdapter.dll
              !**\obj\**
            searchFolder: '$(System.DefaultWorkingDirectory)\Sources'
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Artifact'
          inputs:
            targetPath: '$(build.artifactstagingdirectory)\Packages'
            artifact: 'packages'
            publishLocation: 'pipeline'
