//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiLinq.ProcessTemplates.Scrum {
  using WiLinq.LinqProvider;
  
  
  [WiLinq.LinqProvider.WorkItemTypeAttribute("Task")]
  public partial class Task : WiLinq.LinqProvider.GenericWorkItem {
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ActivatedBy")]
    public virtual string ActivatedBy {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.Common.ActivatedBy");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.Common.ActivatedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ActivatedDate")]
    public virtual System.Nullable<System.DateTime> ActivatedDate {
      get {
        return this.GetStructField<System.DateTime>("Microsoft.VSTS.Common.ActivatedDate");
      }
      set {
        this.SetStructField<System.DateTime>("Microsoft.VSTS.Common.ActivatedDate", value);
      }
    }
    
    /// <summary>Type of work involved</summary>
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.Activity")]
    public virtual string Activity {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.Common.Activity");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.Common.Activity", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.GetRefField<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.GetStructField<System.DateTime>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.BacklogPriority")]
    public virtual System.Nullable<double> BacklogPriority {
      get {
        return this.GetStructField<double>("Microsoft.VSTS.Common.BacklogPriority");
      }
      set {
        this.SetStructField<double>("Microsoft.VSTS.Common.BacklogPriority", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.CMMI.Blocked")]
    public virtual string Blocked {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.CMMI.Blocked");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.CMMI.Blocked", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.GetStructField<System.DateTime>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.SetStructField<System.DateTime>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.CommentCount")]
    public virtual System.Nullable<long> CommentCount {
      get {
        return this.GetStructField<long>("System.CommentCount");
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.Parent")]
    public virtual System.Nullable<long> Parent {
      get {
        return this.GetStructField<long>("System.Parent");
      }
    }
    
    /// <summary>Importance to business</summary>
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.Priority")]
    public virtual System.Nullable<long> Priority {
      get {
        return this.GetStructField<long>("Microsoft.VSTS.Common.Priority");
      }
      set {
        this.SetStructField<long>("Microsoft.VSTS.Common.Priority", value);
      }
    }
    
    /// <summary>An estimate of the number of units of work remaining to complete this task</summary>
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Scheduling.RemainingWork")]
    public virtual System.Nullable<double> RemainingWork {
      get {
        return this.GetStructField<double>("Microsoft.VSTS.Scheduling.RemainingWork");
      }
      set {
        this.SetStructField<double>("Microsoft.VSTS.Scheduling.RemainingWork", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.RemoteLinkCount")]
    public virtual System.Nullable<long> RemoteLinkCount {
      get {
        return this.GetStructField<long>("System.RemoteLinkCount");
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ResolvedBy")]
    public virtual string ResolvedBy {
      get {
        return this.GetRefField<string>("Microsoft.VSTS.Common.ResolvedBy");
      }
      set {
        this.SetRefField<string>("Microsoft.VSTS.Common.ResolvedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.ResolvedDate")]
    public virtual System.Nullable<System.DateTime> ResolvedDate {
      get {
        return this.GetStructField<System.DateTime>("Microsoft.VSTS.Common.ResolvedDate");
      }
      set {
        this.SetStructField<System.DateTime>("Microsoft.VSTS.Common.ResolvedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.GetStructField<System.DateTime>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.FieldAttribute("Microsoft.VSTS.Common.StateChangeDate")]
    public virtual System.Nullable<System.DateTime> StateChangeDate {
      get {
        return this.GetStructField<System.DateTime>("Microsoft.VSTS.Common.StateChangeDate");
      }
      set {
        this.SetStructField<System.DateTime>("Microsoft.VSTS.Common.StateChangeDate", value);
      }
    }
  }
}
